### ISSUE TITLE
fe 封装的http库 可否换个名称

### ISSUE THREAD

**Issue by liuyangc3** [open-falcon/fe#9]
如果main.go代码里引入 pprof，会有冲突

```
import (
  _ "net/http/pprof"
 "github.com/open-falcon/fe/http"
)
func main() {
  ...
    model.InitDatabase()
    cache.InitCache()

    go func() {
        log.Println(http.ListenAndServe("localhost:6060", nil))
    }()
    http.Start()
}
```

编译

```
[root@fe]# ./control build
# _/opt/open-falcon/fe
./main.go:37: undefined: "github.com/open-falcon/fe/http".ListenAndServe
```

**Comment by laiwei** [comment]
后续可以改改。。。

嗯，你可以先把pprof import为另外一个名字，可以吗

**Comment by liuyangc3** [comment]
@laiwei 

好像也不行

**Comment by liuyangc3** [comment]
这个是调用  http ListenAndServe  加个侦听端口
还不是显式调用 pprof 

我改名pprof  后 fe的 http 也没有ListenAndServe方法啊

**Comment by liuyangc3** [comment]
@laiwei 改名可行

不过还是建议 不要和官方标准库重名

另外我有点不明白 import 的这个写法

```
import (
 "github.com/open-falcon/fe/http"
)
```

 http是fe的一个package 子目录
结果我在调试的时候，IDE 又在 gopath下面重新 安装了一遍  "github.com/open-falcon/fe/http"

除非这么写，不然我对http模块的修改，编译后都不生效， 请问子模块的引用写成上面的方式是有什么具体的原因吗

```
import (
 "./http"
)
```
